[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_project = "4Cfgg3SY8iWJm6YmEbXZpAvmnghPbGKfPT8HBG3TizX2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
